#!/bin/bash

set -e

HOST=${1:-127.0.0.1:5984}
DB=baseball

curl -X PUT http://$HOST/$DB

DESIGN=messages

curl -X PUT --data-binary @- http://$HOST/$DB/_design/$DESIGN <<JS
{
   "_id": "_design/messages",
   "language": "javascript",
   "views": {
       "message_history": {
           "map": "function(doc) {\n\tif(doc.type === 'message'){\n\t\tvar mess = {from: doc.from, id: doc._id};\n\t\tif(doc.body){\n\t\t\tmess.body = doc.body;\n\t\t}\n\t\tif(doc.image){\n\t\t\tmess.image = doc.image;\n\t\t}\n\t\temit([doc.thread,doc._id],mess);\n\t}\n}"
       }
   }
}
JS

DESIGN=users

curl -X PUT --data-binary @- http://$HOST/$DB/_design/$DESIGN <<JS
{
   "_id": "_design/users",
   "language": "javascript",
   "views": {
       "threads": {
           "map": "function(doc) {\n    if(doc.type === 'thread') {\n        var thread = \n        {\n            id: doc._id,\n            users: doc.users,\n            creator: doc.creator\n        };\n        if(doc.name){\n            thread.name = doc.name;\n        }\n        doc.users.forEach(function(user) {\n                emit(user,thread);\n        });\n        \n    }\n}"
       }
   }
}
JS
